spring.application.name=itops-backend
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=itops;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=YourStrong!Passw0rd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true