name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Starts MS SQL Server in the runner container environment
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'   # Updated from '17' to '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build and Run Tests with Maven
      run: mvn -B clean package --file pom.xml
